[package]
name = "bevy_pathfinding"
version = "0.1.0"
authors = ["RichoDemus <git@richodemus.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5"
pathfinding = "2.1"
